DROP SEQUENCE CART_SEQ;
CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE CART;
CREATE TABLE CART
(
	CNO NUMBER PRIMARY KEY, 
	MNO NUMBER REFERENCES MEMBER (MNO), 
	PNO NUMBER REFERENCES PRODUCT (PNO), 
	CAMOUNT NUMBER, 
	COPTION VARCHAR2(100)
);