DROP SEQUENCE FAQ_SEQ;
CREATE SEQUENCE FAQ_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE FAQ;
CREATE TABLE FAQ
(
	FNO NUMBER PRIMARY KEY,
	FTITLE VARCHAR2(300),
	FCONTENT VARCHAR2(4000) NOT NULL,
	FWRITER VARCHAR2(50),
	FREGDATE DATE
);