DROP SEQUENCE ROLE_SEQ;
CREATE SEQUENCE ROLE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE ROLE;
CREATE TABLE ROLE
(
	RNO NUMBER PRIMARY KEY,
	MNO NUMBER REFERENCES MEMBER (MNO),	
	ROLE VARCHAR2(30) NOT NULL
);